baseURL = 'https://cloudwhite123.github.io/cloudwhite.io/'
languageCode = 'en-us'
title = 'CloudWhite Tech Blog'
theme = 'hugo-blog-awesome'
#disableKinds = ["RSS"]
[author]
    name = "CloudWhite"
    email = "your-email@example.com"


[params]
    description = "SSD Firmware Security Engineer"
    
    # 錯誤寫法：author = "CloudWhite"
    # 正確寫法：必須是物件格式
    [params.author]
        name = "CloudWhite"
        bio = "SSD Firmware Security Engineer / Tech Enthusiast"
        avatar = "" # 如果還沒有圖片，可以先隨便填一個路徑或留空串
